import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import "@/styles/landing.css";
import AuthContext from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContext>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <nav className="site-nav">
            <a className="site-nav__brand" href="/">
              That's Meeting
            </a>
            <div className="site-nav__spacer" />
            <a href="/sign-in">로그인</a>
            <a href="/sign-up">가입</a>
          </nav>
          {children}
        </body>
      </AuthContext>
    </html>
  );
}
